package temporizador.tlsa2;

import java.awt.Color;
import static java.awt.Color.RED;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.nio.charset.Charset;
import java.text.SimpleDateFormat;
//import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JTextField;
import javax.swing.JTextPane;
import javax.swing.Timer;

/**
 *
 * @author Samila Oliveira */

public class Panel extends javax.swing.JFrame {
    
    private Timer timer;
    private int hours;
    private int minutes;
    private int seconds;
    private boolean isCountingDown = true;
    private JComboBox<String> comboBox;
//    Date dataSistema = new Date();
 
    public Panel() {
        initComponents();
        this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/images/icone-TLSA.jpg")).getImage());
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
      //  dataLabel.setText(formato.format(dataSistema));
        
        
              
        timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if(isCountingDown) {
                    if(seconds < 0){
                        if(minutes > 0) {
                            minutes--;
                            seconds = 59;
                        } else if(hours > 0){
                            hours--;
                            minutes = 59;
                            seconds = 59;
                        } else {
                            isCountingDown = false;
                            seconds = 0;
                            hoursField.setDisabledTextColor(Color.RED);
                            minutesField.setDisabledTextColor(Color.RED);
                            secondsField.setDisabledTextColor(Color.RED);
                            // cor do texto será alterada para vermelho 
                            // quando o campo estiver desabilitado.
                        }
                    }
                } else {
                    if(seconds > 59){
                        seconds = 0;
                        minutes++;
                    }
                    if(minutes > 59){
                        minutes = 0;
                        hours++;
                    }
                }
                
                String sign = isCountingDown ? "" : "-";
                hoursField.setText(sign + String.format("%02d", hours));
                minutesField.setText(String.format("%02d", minutes));
                secondsField.setText(String.format("%02d", seconds));
                if(isCountingDown) seconds --;
                else {
                    hoursField.setDisabledTextColor(Color.RED);
                    minutesField.setDisabledTextColor(Color.RED);
                    secondsField.setDisabledTextColor(Color.RED);
                    seconds++;
                    timeout.setText("Tempo Esgotado!");
                    
                    
                }
            }
        });
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem3 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem4 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem5 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem6 = new javax.swing.JRadioButtonMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jButtonIniciar = new javax.swing.JButton();
        jButtonPausar = new javax.swing.JButton();
        jButtonReiniciar = new javax.swing.JButton();
        hoursField = new javax.swing.JTextFieldSomenteNumeros(2);
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        minutesField = new javax.swing.JTextFieldSomenteNumeros(2);
        secondsField = new javax.swing.JTextFieldSomenteNumeros(2);
        jLabel5 = new javax.swing.JLabel();
        jCmbBoxLogo = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        imageLogo = new javax.swing.JLabel();
        timeout = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        VisuAgenda = new javax.swing.JMenuItem();
        EdiAgenda = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        EditarEmpresa = new javax.swing.JMenuItem();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("jRadioButtonMenuItem2");

        jRadioButtonMenuItem3.setSelected(true);
        jRadioButtonMenuItem3.setText("jRadioButtonMenuItem3");

        jRadioButtonMenuItem4.setSelected(true);
        jRadioButtonMenuItem4.setText("jRadioButtonMenuItem4");

        jRadioButtonMenuItem5.setSelected(true);
        jRadioButtonMenuItem5.setText("jRadioButtonMenuItem5");

        jRadioButtonMenuItem6.setSelected(true);
        jRadioButtonMenuItem6.setText("jRadioButtonMenuItem6");

        jMenu3.setText("jMenu3");

        jMenu2.setText("File");
        jMenuBar2.add(jMenu2);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Temporizador TLSA");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(700, 620));
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Reunião");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(290, 200, 100, 40);

        jButtonIniciar.setBackground(new java.awt.Color(51, 51, 51));
        jButtonIniciar.setText("Iniciar");
        jButtonIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIniciarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonIniciar);
        jButtonIniciar.setBounds(140, 250, 80, 20);

        jButtonPausar.setBackground(new java.awt.Color(51, 51, 51));
        jButtonPausar.setText("Pausar");
        jButtonPausar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPausarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPausar);
        jButtonPausar.setBounds(300, 250, 80, 20);

        jButtonReiniciar.setBackground(new java.awt.Color(51, 51, 51));
        jButtonReiniciar.setText("Reiniciar");
        jButtonReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReiniciarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonReiniciar);
        jButtonReiniciar.setBounds(460, 250, 80, 20);

        hoursField.setBackground(java.awt.SystemColor.controlLtHighlight);
        hoursField.setFont(new java.awt.Font("Arial", 1, 70)); // NOI18N
        hoursField.setForeground(new java.awt.Color(0, 0, 0));
        hoursField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        hoursField.setText("00");
        hoursField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        hoursField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hoursFieldActionPerformed(evt);
            }
        });
        getContentPane().add(hoursField);
        hoursField.setBounds(110, 280, 140, 110);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(100, 230, 0, 0);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Temporizador");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(220, 140, 250, 50);

        minutesField.setBackground(new java.awt.Color(255, 255, 255));
        minutesField.setFont(new java.awt.Font("Arial", 1, 70)); // NOI18N
        minutesField.setForeground(new java.awt.Color(0, 0, 0));
        minutesField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        minutesField.setText("00");
        minutesField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        minutesField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minutesFieldActionPerformed(evt);
            }
        });
        getContentPane().add(minutesField);
        minutesField.setBounds(270, 280, 140, 110);

        secondsField.setBackground(new java.awt.Color(255, 255, 255));
        secondsField.setFont(new java.awt.Font("Arial", 1, 70)); // NOI18N
        secondsField.setForeground(new java.awt.Color(0, 0, 0));
        secondsField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        secondsField.setText("00");
        secondsField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        secondsField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                secondsFieldFocusLost(evt);
            }
        });
        secondsField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondsFieldActionPerformed(evt);
            }
        });
        getContentPane().add(secondsField);
        secondsField.setBounds(430, 280, 140, 110);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/temporizador.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(90, 200, 500, 230);

        jCmbBoxLogo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione a empresa", "Nenhuma", "CSN", "TLSA", "FTL" }));
        jCmbBoxLogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmbBoxLogoActionPerformed(evt);
            }
        });
        getContentPane().add(jCmbBoxLogo);
        jCmbBoxLogo.setBounds(240, 10, 150, 22);

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(390, 10, 46, 22);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CSN_rodapé.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 480, 250, 70);

        imageLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(imageLogo);
        imageLogo.setBounds(230, 30, 220, 110);

        timeout.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        timeout.setForeground(new java.awt.Color(255, 0, 0));
        timeout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(timeout);
        timeout.setBounds(223, 436, 230, 30);

        jMenu1.setText("Agenda");

        VisuAgenda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        VisuAgenda.setText("Criar/Visualizar Agenda");
        VisuAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisuAgendaActionPerformed(evt);
            }
        });
        jMenu1.add(VisuAgenda);

        EdiAgenda.setText("Editar Agenda");
        EdiAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdiAgendaActionPerformed(evt);
            }
        });
        jMenu1.add(EdiAgenda);

        jMenuItem1.setText("Fechar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu5.setText("Empresa");

        EditarEmpresa.setText("Editar empresa");
        EditarEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarEmpresaActionPerformed(evt);
            }
        });
        jMenu5.add(EditarEmpresa);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIniciarActionPerformed
          
        hours = Integer.parseInt(hoursField.getText());
        minutes = Integer.parseInt(minutesField.getText());
        seconds = Integer.parseInt(secondsField.getText());
        timer.start();
        hoursField.setEnabled(false);
        minutesField.setEnabled(false);
        secondsField.setEnabled(false);
        hoursField.setDisabledTextColor(Color.BLACK);
        minutesField.setDisabledTextColor(Color.BLACK);
        secondsField.setDisabledTextColor(Color.BLACK);
        timeout.setText(""); //limpa o texto quando o timer iniciar
        
        if(minutes > 59 || seconds > 59) {
        throw new IllegalArgumentException("Os valores de minutos e segundos não devem ultrapassar 59.");
    }
        
    }//GEN-LAST:event_jButtonIniciarActionPerformed

    private void jButtonPausarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPausarActionPerformed
        timer.stop();
    }//GEN-LAST:event_jButtonPausarActionPerformed

    private void minutesFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minutesFieldActionPerformed
         minutesField = new JTextField("00");
          if(isCountingDown = false){
             minutesField.setDisabledTextColor(Color.RED);
          }
          
          
    }//GEN-LAST:event_minutesFieldActionPerformed

    private void hoursFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hoursFieldActionPerformed
       hoursField = new JTextField("00");
       if(isCountingDown = false){
          hoursField.setDisabledTextColor(Color.RED);
       }
    }//GEN-LAST:event_hoursFieldActionPerformed

    private void jButtonReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReiniciarActionPerformed

        timer.stop();
        
        hours = 0;
        minutes = 0;
        seconds = 0;
        
        hoursField.setText(String.format("%02d", hours));
        minutesField.setText(String.format("%02d", minutes));
        secondsField.setText(String.format("%02d", seconds));
        
        hoursField.setEnabled(true);
        minutesField.setEnabled(true);        
        secondsField.setEnabled(true);
        
        hoursField.setForeground(Color.BLACK);       
        minutesField.setForeground(Color.BLACK);
        secondsField.setForeground(Color.BLACK);
        
        isCountingDown = true; //reinicia a contagem regressiva
        
        timeout.setText(""); //limpa o texto quando o timer iniciar
        
    }//GEN-LAST:event_jButtonReiniciarActionPerformed

    private void secondsFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_secondsFieldFocusLost
        
    }//GEN-LAST:event_secondsFieldFocusLost

    private void secondsFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secondsFieldActionPerformed
        secondsField = new JTextField("00");
        if(isCountingDown = false){
           secondsField.setDisabledTextColor(Color.RED);
        }
    }//GEN-LAST:event_secondsFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String selectedOption = (String) jCmbBoxLogo.getSelectedItem();
        switch (selectedOption) {
            case "CSN":
            imageLogo.setIcon(new ImageIcon(getClass().getResource("/images/CSN.png")));
            break;
            case "TLSA":
            imageLogo.setIcon(new ImageIcon(getClass().getResource("/images/TLSA.png")));
            break;
            case "FTL":
            imageLogo.setIcon(new ImageIcon(getClass().getResource("/images/ftl.png")));
            break;
            default:
            imageLogo.setIcon(null);
            break;
        }
        jCmbBoxLogo.setVisible(false);
        jButton1.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCmbBoxLogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmbBoxLogoActionPerformed
        String[] options = {"Nenhuma", "CSN", "TLSA", "FTL"};
        JComboBox<String> comboBox = new JComboBox<>(options);

    }//GEN-LAST:event_jCmbBoxLogoActionPerformed

    private void EditarEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarEmpresaActionPerformed
        jCmbBoxLogo.setVisible(true);
        jButton1.setVisible(true);
    }//GEN-LAST:event_EditarEmpresaActionPerformed

    private void VisuAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisuAgendaActionPerformed
       /* VisuAgenda agenda = null;
        File file = new File(System.getProperty("java.io.tmpdir") + File.separator + "agenda.txt");
        try{
            if(file.exists() && file.canRead()){
            BufferedReader br = new BufferedReader(new FileReader(file));
            
            StringBuilder builder = new StringBuilder();
            String line;
            while((line = br.readLine()) != null){
                builder.append(line);
            }
               
            
             agenda = new VisuAgenda(builder.toString());
             System.out.println("TEXTO: " + builder);
                
            }
        }catch (Exception e){
            e.printStackTrace();
        } */
        AgendaTeste at = new AgendaTeste();
        at.setVisible(true);
       
       
    }//GEN-LAST:event_VisuAgendaActionPerformed

    private void EdiAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdiAgendaActionPerformed

        Agenda ag = new Agenda();
        ag.setVisible(true);
    }//GEN-LAST:event_EdiAgendaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        java.awt.EventQueue.invokeLater(() -> {
            new Panel().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem EdiAgenda;
    private javax.swing.JMenuItem EditarEmpresa;
    private javax.swing.JMenuItem VisuAgenda;
    private javax.swing.JTextField hoursField;
    private javax.swing.JLabel imageLogo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonIniciar;
    private javax.swing.JButton jButtonPausar;
    private javax.swing.JButton jButtonReiniciar;
    private javax.swing.JComboBox<String> jCmbBoxLogo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem3;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem4;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem5;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem6;
    private javax.swing.JTextField minutesField;
    private javax.swing.JTextField secondsField;
    private javax.swing.JLabel timeout;
    // End of variables declaration//GEN-END:variables

}
