package temporizador.tlsa2;

import java.awt.Color;
import static java.awt.Color.RED;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.nio.charset.Charset;
import java.text.SimpleDateFormat;
//import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JTextField;
import javax.swing.JTextPane;
import javax.swing.Timer;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import service.ReadFileService;

/**
 *
 * @author Samila Oliveira */

public class Panel extends javax.swing.JFrame {
    
    private Timer timer;
    private int hours;
    private int minutes;
    private int seconds;
    private boolean isCountingDown = true;
    private JComboBox<String> comboBox;
//    Date dataSistema = new Date();
 
    public Panel() {
        initComponents();
        this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/images/icone-TLSA.jpg")).getImage());
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
      //  dataLabel.setText(formato.format(dataSistema));
      
      //jInternalFrame1.setUndecorated(true);
      
      //código para executar o programa em tela cheia
      //setExtendedState(MAXIMIZED_BOTH); 
              
        timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if(isCountingDown) {
                    if(seconds < 0){
                        if(minutes > 0) {
                            minutes--;
                            seconds = 59;
                        } else if(hours > 0){
                            hours--;
                            minutes = 59;
                            seconds = 59;
                        } else {
                            isCountingDown = false;
                            seconds = 0;
                            hoursField.setDisabledTextColor(Color.RED);
                            minutesField.setDisabledTextColor(Color.RED);
                            secondsField.setDisabledTextColor(Color.RED);
                            // cor do texto será alterada para vermelho 
                            // quando o campo estiver desabilitado.
                        }
                    }
                } else {
                    if(seconds > 59){
                        seconds = 0;
                        minutes++;
                    }
                    if(minutes > 59){
                        minutes = 0;
                        hours++;
                    }
                }
                
                String sign = isCountingDown ? "" : "-";
                hoursField.setText(sign + String.format("%02d", hours));
                minutesField.setText(String.format("%02d", minutes));
                secondsField.setText(String.format("%02d", seconds));
                if(isCountingDown) seconds --;
                else {
                    hoursField.setDisabledTextColor(Color.RED);
                    minutesField.setDisabledTextColor(Color.RED);
                    secondsField.setDisabledTextColor(Color.RED);
                    seconds++;
                    timeout.setText("Tempo Esgotado!");
                    
                    
                }
            }
        });
        // Deixa invisivel a barra de título do internal frame
        jInternalFrame1.setUI(new BasicInternalFrameUI(jInternalFrame1) {
            public void installUI(JComponent c) {
                super.installUI(c);
                ((javax.swing.plaf.basic.BasicInternalFrameUI) this).setNorthPane(null);
            }
        });
        
        jInternalFrame1.setBorder(null); // retira as bordas 
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem3 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem4 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem5 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem6 = new javax.swing.JRadioButtonMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jFrame3 = new javax.swing.JFrame();
        jLabel2 = new javax.swing.JLabel();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jCmbBoxLogo = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        imageLogo = new javax.swing.JLabel();
        timeout = new javax.swing.JLabel();
        jButtonPausar = new javax.swing.JButton();
        jButtonIniciar = new javax.swing.JButton();
        jButtonReiniciar = new javax.swing.JButton();
        secondsField = new javax.swing.JTextFieldSomenteNumeros(2);
        minutesField = new javax.swing.JTextFieldSomenteNumeros(2);
        hoursField = new javax.swing.JTextFieldSomenteNumeros(2);
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        VisuAgenda = new javax.swing.JMenuItem();
        EdiAgenda = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        EditarEmpresa = new javax.swing.JMenuItem();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("jRadioButtonMenuItem2");

        jRadioButtonMenuItem3.setSelected(true);
        jRadioButtonMenuItem3.setText("jRadioButtonMenuItem3");

        jRadioButtonMenuItem4.setSelected(true);
        jRadioButtonMenuItem4.setText("jRadioButtonMenuItem4");

        jRadioButtonMenuItem5.setSelected(true);
        jRadioButtonMenuItem5.setText("jRadioButtonMenuItem5");

        jRadioButtonMenuItem6.setSelected(true);
        jRadioButtonMenuItem6.setText("jRadioButtonMenuItem6");

        jMenu3.setText("jMenu3");

        jMenu2.setText("File");
        jMenuBar2.add(jMenu2);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Temporizador TLSA");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(1080, 831));
        setName("Panel"); // NOI18N
        setSize(new java.awt.Dimension(1080, 831));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(jLabel2, gridBagConstraints);

        jInternalFrame1.setBorder(null);
        jInternalFrame1.setVisible(true);
        jInternalFrame1.getContentPane().setLayout(null);

        jCmbBoxLogo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione a empresa", "Nenhuma", "CSN", "TLSA", "FTL" }));
        jCmbBoxLogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmbBoxLogoActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jCmbBoxLogo);
        jCmbBoxLogo.setBounds(460, 10, 160, 20);

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jButton1);
        jButton1.setBounds(630, 10, 60, 20);

        imageLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imageLogo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        imageLogo.setPreferredSize(new java.awt.Dimension(1080, 720));
        jInternalFrame1.getContentPane().add(imageLogo);
        imageLogo.setBounds(440, 40, 270, 140);

        timeout.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        timeout.setForeground(new java.awt.Color(255, 0, 0));
        timeout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jInternalFrame1.getContentPane().add(timeout);
        timeout.setBounds(430, 540, 310, 50);

        jButtonPausar.setBackground(new java.awt.Color(51, 51, 51));
        jButtonPausar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButtonPausar.setText("Pausar");
        jButtonPausar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPausarActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jButtonPausar);
        jButtonPausar.setBounds(530, 250, 110, 30);

        jButtonIniciar.setBackground(new java.awt.Color(51, 51, 51));
        jButtonIniciar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButtonIniciar.setText("Iniciar");
        jButtonIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIniciarActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jButtonIniciar);
        jButtonIniciar.setBounds(290, 250, 110, 30);

        jButtonReiniciar.setBackground(new java.awt.Color(51, 51, 51));
        jButtonReiniciar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButtonReiniciar.setText("Reiniciar");
        jButtonReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReiniciarActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jButtonReiniciar);
        jButtonReiniciar.setBounds(760, 250, 110, 30);

        secondsField.setBackground(new java.awt.Color(255, 255, 255));
        secondsField.setFont(new java.awt.Font("Arial", 1, 100)); // NOI18N
        secondsField.setForeground(new java.awt.Color(0, 0, 0));
        secondsField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        secondsField.setText("00");
        secondsField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        secondsField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                secondsFieldFocusLost(evt);
            }
        });
        secondsField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondsFieldActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(secondsField);
        secondsField.setBounds(720, 300, 201, 157);

        minutesField.setBackground(new java.awt.Color(255, 255, 255));
        minutesField.setFont(new java.awt.Font("Arial", 1, 100)); // NOI18N
        minutesField.setForeground(new java.awt.Color(0, 0, 0));
        minutesField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        minutesField.setText("00");
        minutesField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        minutesField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minutesFieldActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(minutesField);
        minutesField.setBounds(480, 300, 204, 157);

        hoursField.setBackground(java.awt.SystemColor.controlLtHighlight);
        hoursField.setFont(new java.awt.Font("Arial", 1, 100)); // NOI18N
        hoursField.setForeground(new java.awt.Color(0, 0, 0));
        hoursField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        hoursField.setText("00");
        hoursField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        hoursField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hoursFieldActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(hoursField);
        hoursField.setBounds(240, 300, 204, 157);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/temporizador_t.png"))); // NOI18N
        jInternalFrame1.getContentPane().add(jLabel5);
        jLabel5.setBounds(210, 190, 750, 330);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CSN_rodape-.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jInternalFrame1.getContentPane().add(jLabel3);
        jLabel3.setBounds(380, 620, 400, 110);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 1154;
        gridBagConstraints.ipady = 747;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 13);
        getContentPane().add(jInternalFrame1, gridBagConstraints);

        jMenu1.setText("Agenda");

        VisuAgenda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        VisuAgenda.setText("Visualizar Agenda");
        VisuAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisuAgendaActionPerformed(evt);
            }
        });
        jMenu1.add(VisuAgenda);

        EdiAgenda.setText("Editar Agenda");
        EdiAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdiAgendaActionPerformed(evt);
            }
        });
        jMenu1.add(EdiAgenda);

        jMenuItem1.setText("Fechar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu5.setText("Empresa");

        EditarEmpresa.setText("Editar empresa");
        EditarEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarEmpresaActionPerformed(evt);
            }
        });
        jMenu5.add(EditarEmpresa);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(1206, 787));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIniciarActionPerformed
          
        hours = Integer.parseInt(hoursField.getText());
        minutes = Integer.parseInt(minutesField.getText());
        seconds = Integer.parseInt(secondsField.getText());
        timer.start();
        hoursField.setEnabled(false);
        minutesField.setEnabled(false);
        secondsField.setEnabled(false);
        hoursField.setDisabledTextColor(Color.BLACK);
        minutesField.setDisabledTextColor(Color.BLACK);
        secondsField.setDisabledTextColor(Color.BLACK);
        timeout.setText(""); //limpa o texto quando o timer iniciar
        
        if(minutes > 59 || seconds > 59) {
        throw new IllegalArgumentException("Os valores de minutos e segundos não devem ultrapassar 59.");
    }
        
    }//GEN-LAST:event_jButtonIniciarActionPerformed

    private void jButtonPausarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPausarActionPerformed
        timer.stop();
    }//GEN-LAST:event_jButtonPausarActionPerformed

    private void minutesFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minutesFieldActionPerformed
         minutesField = new JTextField("00");
          if(isCountingDown = false){
             minutesField.setDisabledTextColor(Color.RED);
          }
          
          
    }//GEN-LAST:event_minutesFieldActionPerformed

    private void hoursFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hoursFieldActionPerformed
       hoursField = new JTextField("00");
       if(isCountingDown = false){
          hoursField.setDisabledTextColor(Color.RED);
       }
    }//GEN-LAST:event_hoursFieldActionPerformed

    private void jButtonReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReiniciarActionPerformed

        timer.stop();
        
        hours = 0;
        minutes = 0;
        seconds = 0;
        
        hoursField.setText(String.format("%02d", hours));
        minutesField.setText(String.format("%02d", minutes));
        secondsField.setText(String.format("%02d", seconds));
        
        hoursField.setEnabled(true);
        minutesField.setEnabled(true);        
        secondsField.setEnabled(true);
        
        hoursField.setForeground(Color.BLACK);       
        minutesField.setForeground(Color.BLACK);
        secondsField.setForeground(Color.BLACK);
        
        isCountingDown = true; //reinicia a contagem regressiva
        
        timeout.setText(""); //limpa o texto quando o timer iniciar
        
    }//GEN-LAST:event_jButtonReiniciarActionPerformed

    private void secondsFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_secondsFieldFocusLost
        
    }//GEN-LAST:event_secondsFieldFocusLost

    private void secondsFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secondsFieldActionPerformed
        secondsField = new JTextField("00");
        if(isCountingDown = false){
           secondsField.setDisabledTextColor(Color.RED);
        }
    }//GEN-LAST:event_secondsFieldActionPerformed
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String selectedOption = (String) jCmbBoxLogo.getSelectedItem();
        switch (selectedOption) {
            case "CSN":
            imageLogo.setIcon(new ImageIcon(getClass().getResource("/images/CSN.png")));
            break;
            case "TLSA":
            imageLogo.setIcon(new ImageIcon(getClass().getResource("/images/TLSA.png")));
            break;
            case "FTL":
            imageLogo.setIcon(new ImageIcon(getClass().getResource("/images/ftl.png")));
            break;
            default:
            imageLogo.setIcon(null);
            break;
        }
        jCmbBoxLogo.setVisible(false);
        jButton1.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCmbBoxLogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmbBoxLogoActionPerformed
        String[] options = {"Nenhuma", "CSN", "TLSA", "FTL"};
        JComboBox<String> comboBox = new JComboBox<>(options);

    }//GEN-LAST:event_jCmbBoxLogoActionPerformed

    private void EditarEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarEmpresaActionPerformed
        jCmbBoxLogo.setVisible(true);
        jButton1.setVisible(true);
    }//GEN-LAST:event_EditarEmpresaActionPerformed

    private void VisuAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisuAgendaActionPerformed
       VisuAgenda agenda = new VisuAgenda(new ReadFileService().read());
        
      //  AgendaTeste at = new AgendaTeste();
        agenda.setVisible(true);
       
    }//GEN-LAST:event_VisuAgendaActionPerformed

    private void EdiAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdiAgendaActionPerformed

        Agenda ag = new Agenda(new ReadFileService().read());
        ag.setVisible(true);
    }//GEN-LAST:event_EdiAgendaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized

    }//GEN-LAST:event_formComponentResized

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();

        // Obtenha a largura e a altura
        int width = screenSize.width;
        int height = screenSize.height;
        
        java.awt.EventQueue.invokeLater(() -> {
            new Panel().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem EdiAgenda;
    private javax.swing.JMenuItem EditarEmpresa;
    private javax.swing.JMenuItem VisuAgenda;
    private javax.swing.JTextField hoursField;
    private javax.swing.JLabel imageLogo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonIniciar;
    private javax.swing.JButton jButtonPausar;
    private javax.swing.JButton jButtonReiniciar;
    private javax.swing.JComboBox<String> jCmbBoxLogo;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JFrame jFrame3;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem3;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem4;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem5;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem6;
    private javax.swing.JTextField minutesField;
    private javax.swing.JTextField secondsField;
    private javax.swing.JLabel timeout;
    // End of variables declaration//GEN-END:variables

}
